<?php
// $Id$

/**
 * @file
 * Contains Pasargad Bank Payment API implementations and helpers.
 */

/**
 * API function to create content's XML representation.
 *
 * @param $content
 *   An array of required content items as per defined in gateway docs.
 *
 * @return
 *   XML representation of passed $content.
 *
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function pasargad_xml($content) {

}

/**
 * API function to sign XML representation of content.
 *
 * @param $xml
 *   XML representation of required content as per defined in docs.
 * @param $private_key
 *   Accessible system path to private key file.
 *
 * @return
 *   Either signed XML content or FALSE on fail.
 *
 * @see pasargad_xml()
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function pasargad_sign($xml, $private_key) {

}

/**
 * API function to request Pasargad Bank gateway.
 *
 * @param $gateway
 *   Pasargad Bank gateway controller URI.
 *
 * @return
 *   An array of request response.
 *
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function pasargad_request($gateway = 'https://paypaad.bankpasargad.com/PaymentController') {

}

/**
 * API function to request Pasargad Bank gateway.
 *
 * @param $gateway
 *   Pasargad Bank gateway trace URI.
 *
 * @return
 *   An array of request response.
 *
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function pasargad_trace($gateway = 'https://paypaad.bankpasargad.com/PaymentTrace') {

}

/**
 * Internal helper to perform a cURL POST request.
 *
 * @param $destination
 *   cURL destination URI.
 * @param $params
 *   An array of POST parameters to be sent.
 *
 * @return
 *   Either the request response or FALSE on fail.
 *
 * @see pasargad_trace()
 * @see pasargad_request()
 * @see http://php.net/manual/en/function.curl-setopt.php
 */
function _pasargard_curl($destination, $params = array()) {
  // cURL is a dependency.
  if (!extension_loaded('curl')) {
    return FALSE;
  }

  // Initiate cURL session, set options.
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_URL, $destination);
  curl_setopt($curl, CURLOPT_HEADER, FALSE);
  curl_setopt($curl, CURLOPT_FAILONERROR, TRUE);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
  // Follow any "Location: " header,
  // CURLOPT_MAXREDIRS won't be set.
  curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
  // Set POST request options.
  curl_setopt($curl, CURLOPT_POST, TRUE);CURLOPT_MAXREDIRS
  curl_setopt($curl, CURLOPT_POSTFIELDS, $params);
  // Run rabbit, run!
  $response = curl_exec($curl);

  // Close the session & return the response.
  curl_close($curl);
  return (string) $response;
}

