<?php
// $Id$

/**
 * @file
 * Contains Pasargad Bank Payment API implementations and helpers.
 */

/**
 * API function to create content's XML representation.
 *
 * @param $content
 *   An array of required content items as per defined in gateway docs.
 *   - time_stamp: Request date in "Y/m/d H:i:s" format. (optional)
 *   - invoice_date: Invoice date in an optional format. (optional)
 *   - invoice_number: Invoice number.
 *   - merchant_code: Store merchant code as per provided by Pasargad Bank.
 *   - terminal_code: Store terminal code as per provided by Pasargad Bank.
 *   - redirect_address: Operation success URL.
 *   - referer_address: Operation failure URL.
 *   - delivery_days: Number of days in which the products will be delivered.
 *   - total_amount: Order total amount.
 *   - buyer_name: Customer name.
 *   - buyer_tel: Customer contact tel.
 *   - delivery_address: Products delivery address.
 * @param $items
 *   Either an array of product arrays, or an array of product objects
 *   which will be injected into $content array as per defined in docs.
 *   - content: Product title.
 *   - count: Number of purchased products.
 *   - fee: Price of product unit.
 *   - amount: fee x count amount.
 *   - description: Product description.
 *
 * @return
 *   XML representation of passed arguments.
 *
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function pasargad_xml($content, $items = array()) {

}

/**
 * API function to sign XML representation of content.
 *
 * @param $xml
 *   XML representation of required content as per defined in docs.
 * @param $private_key
 *   Accessible system path to private key file.
 *
 * @return
 *   Either signed XML content or FALSE on fail.
 *
 * @see pasargad_xml()
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function pasargad_sign($xml, $private_key) {

}

/**
 * API function to request Pasargad Bank gateway.
 *
 * @param $gateway
 *   Pasargad Bank gateway controller URI.
 *
 * @return
 *   An array of request response.
 *
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function pasargad_request($gateway = 'https://paypaad.bankpasargad.com/PaymentController') {

}

/**
 * API function to request Pasargad Bank gateway.
 *
 * @param $gateway
 *   Pasargad Bank gateway trace URI.
 *
 * @return
 *   An array of request response.
 *
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function pasargad_trace($gateway = 'https://paypaad.bankpasargad.com/PaymentTrace') {

}

/**
 * Internal helper to perform a cURL POST request.
 *
 * @param $destination
 *   cURL destination URI.
 * @param $params
 *   Parameters to be sent in a HTTP POST operation,
 *   As per defined in CURLOPT_POSTFIELDS docs.
 *
 * @return
 *   Either the request response or FALSE on fail.
 *
 * @see pasargad_trace()
 * @see pasargad_request()
 * @see http://php.net/manual/en/function.curl-setopt.php
 */
function _pasargard_curl($destination, $params = '') {
  // cURL is a dependency.
  if (!extension_loaded('curl')) {
    return FALSE;
  }

  // Initiate cURL session, set options.
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_URL, $destination);
  curl_setopt($curl, CURLOPT_HEADER, FALSE);
  curl_setopt($curl, CURLOPT_FAILONERROR, TRUE);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
  // Follow any 'Location:' header,
  // CURLOPT_MAXREDIRS won't be set.
  curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
  // Set POST request options.
  curl_setopt($curl, CURLOPT_POST, TRUE);
  curl_setopt($curl, CURLOPT_POSTFIELDS, $params);
  // Run rabbit, run!
  $response = curl_exec($curl);

  // Close the session & return the response.
  curl_close($curl);
  return (string) $response;
}

/**
 * Internal helper to convert an array to XML.
 *
 * @param $array
 *   An array to be converted to XML.
 *
 * @return
 *   Generated XML.
 */
function _pasargad_xml_build($array) {

}

