<?php
// $Id$

/**
 * @file
 * Contains Pasargad Bank Paypaad Payment API implementations and helpers.
 *
 * @todo
 * Hook designation.
 */

/**
 * Defines API version.
 */
define('PAYPAAD_API_VERSION', '2.0');

/**
 * Defines gateway default transaction trace URI.
 */
define('PAYPAAD_TRACE_URI', 'https://paypaad.bankpasargad.com/PaymentTrace');

/**
 * Defines gateway default controller URI.
 */
define('PAYPAAD_CONTROLLER_URI', 'https://paypaad.bankpasargad.com/PaymentController');

/**
 * API function to trace back a transaction status.
 *
 * @param $reference
 *   Transaction reference number.
 * @param $alternative
 *   An array of following data to be used in case
 *   that $reference is not available, see docs, v2, p6.
 *   - invoice_number
 *   - invoice_date
 *   - merchant_code
 *   - terminal_code
 * @param $gateway
 *   Paypaad gateway trace URI.
 * @param $parse
 *   Whether to parse response to an object.
 *
 * @return
 *   Request response consists of following parameters
 *   or FALSE in case of operation failure.
 *   - trace_number
 *   - reference_number
 *   - transaction_date
 *
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function paypaad_trace($reference, $alternative = array(), $gateway = PAYPAAD_TRACE_URI, $parse = TRUE) {
  // Partially check requirements.
  if (!$reference && count($alternative) < 4) {
    return FALSE;
  }
  // Load internal helpers.
  module_load_include('inc', 'paypaad');
  // Setting POST parameters.
  $params = $reference ? array($reference) : $alternative;
  // Dispatch HTTP POST request.
  $response = _pasargard_curl($gateway, $params);
  // Return response as requested.
  return $parse ? simplexml_load_string($response) : $response;
}

/**
 * API function to return a request response.
 *
 * @param $status
 *   Indicates what situation we're in.
 *   - failure: Indicates transaction failure.
 *   - successed: The transaction was successfull, so gateway
 *     has sent following elements via HTTP POST. See docs, v2, p6.
 *     - iD: Invoice date.
 *     - iN: Invoice number.
 *     - tref: Transaction reference as shown to our customer.
 *
 * @return
 *   An array of request response.
 *
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function paypaad_response($status) {
  switch ($status) {
    case 'failure':
      return FALSE;

    case 'success':
      // TODO: Sanitize.
      return array(
        'invoice_date' => $_POST['iD'],
        'invoice_number' => $_POST['iN'],
        'transaction_reference' => $_POST['tref'],
      );
  }
}

/**
 * API function to create invoice content's XML representation.
 *
 * @param $content
 *   An array of required content items as per defined in gateway docs, v2.
 *   - time_stamp: Request date in PHP's "Y/m/d H:i:s" format. (optional)
 *   - invoice_date: Invoice date in an optional format. (optional)
 *   - invoice_number: Invoice number.
 *   - merchant_code: Store merchant code as per provided by Paypaad.
 *   - terminal_code: Store terminal code as per provided by Paypaad.
 *   - redirect_address: Operation success URL.
 *   - referer_address: Operation failure URL.
 *   - delivery_days: Number of days in which the products will be delivered.
 *   - total_amount: Order total amount.
 *   - buyer_name: Customer name.
 *   - buyer_tel: Customer contact tel.
 *   - delivery_address: Products delivery address.
 *   - items: An array of products information as described below.
 * @param $items
 *   An array of product arrays/objects or a single product array/object,
 *   which will be injected into $content array as per defined in docs, v2.
 *   Please note that if $content['items'] is set, this parameter will be ignored.
 *   - content: Product title.
 *   - count: Number of purchased products.
 *   - fee: Price of product unit.
 *   - amount: fee x count amount.
 *   - description: Product description.
 * @param $validate
 *   Whether to validate the generated XML against its DTD.
 *
 * @return
 *   XML representation of passed arguments or FALSE on fail.$items
 *
 * @see _paypaad_xml_build()
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function paypaad_xml(&$content, $items = array(), $validate = FALSE) {
  // Not enough minerals?!
  if (count($content) < 10) {
    return FALSE;
  }
  // Load internal helpers.
  module_load_include('inc', 'paypaad');
  // Get the items array. Any "items" element in content will overwrite the passed $items.
  $items = (isset($content['items']) && !empty($content['items'])) ? $content['items'] : $items;
  unset($content['items']);
  // Default value for time_stamp, if not set.
  $content['time_stamp'] = $content['time_stamp'] ? $content['time_stamp'] : date('Y/m/d H:i:s');
  // Default value for invoice_date, if not set.
  $content['invoice_date'] = $content['invoice_date'] ? $content['invoice_date'] : format_date(time());
  // Wrap a single product array/object to be prepared to be built.
  if (!empty($items) && (is_object($items) || !is_array($items[0]))) {
    $items = array($items);
  }
  // Build and return.
  return _paypaad_xml_build($content, $items, $validate);
}

/**
 * API function that signs XML representation of content.
 *
 * @param $xml
 *   Valid XML representation of content as per defined in docs, v2.
 * @param $private
 *   Private key as per required by openssl_pkey_get_private().
 * @param $passphrase
 *   Private key passphrase in case that the $private is encrypted.
 * @param $public
 *   Optional public key as per required by openssl_verify(),
 *   if set, generated signature will be passed through openssl_verify() to
 *   get verified. Note that $public format differs from the $private one and
 *   should be a openssl_pkey_get_public() valid output or the operation fails.
 *   Am lazy, ya!
 *
 * @return
 *   Either signed XML content or FALSE on fail.
 *
 * @see paypaad_xml()
 * @see http://php.net/manual/en/book.openssl.php
 * @see http://developers.paypaad.ir/docs/readme.pdf
 */
function paypaad_sign($xml, $private, $passphrase = '', $public = FALSE) {
  // Fail if OpenSSL extension is not loaded.
  if (!extension_loaded('openssl')) {
    return FALSE;
  }

  // Get private key if possible.
  if ($private = openssl_pkey_get_private($private, $passphrase)) {
    $sign = '';
    // Generate the signature if possible.
    if (openssl_sign($xml, $sign, $private)) {
      // Verify the signature using public pair, if requested so.
      if (!$public || openssl_verify($xml, $sign, $public) === 1) {
        // Gateway requires a Base64 encoded string
        // of the generated signature, see docs v2, p3.
        return base64_encode($sign);
      }
    }
    // Free $private from memory.
    openssl_free_key($private);
  }
  // Operation failed.
  return FALSE;
}

/**
 * UI helper function that injects required settings fields into the passed form.
 *
 * @param $form
 *   Form (sub)array.
 * @param $id
 *   Module identifier used as field name prefix.
 *
 * @return
 *   Field injected $form array!
 */
function paypaad_settings_fields(&$form = array(), $id = 'paypaad') {
  // Paypaad merchant code.
  $form["{$id}_merchant"] = array(
    '#type' => 'textfield',
    '#title' => t('Merchant Code'),
    '#description' => t('Enter the merchant code provided by Pasargad Bank.'),
    '#default_value' => variable_get("{$id}_merchant", ''),
    '#required' => TRUE,
  );
  // Paypaad terminal code.
  $form["{$id}_terminal"] = array(
    '#type' => 'textfield',
    '#title' => t('Terminal Code'),
    '#description' => t('Enter the terminal code provided by Pasargad Bank.'),
    '#default_value' => variable_get("{$id}_terminal", ''),
    '#required' => TRUE,
  );
  // Maximum product delivery days.
  $form["{$id}_max_delivery_days"] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of delivery days'),
    '#description' => t('Maximum number of days in which the product will be delivered to customer.'),
    '#default_value' => variable_get("{$id}_max_delivery_days", ''),
    '#required' => TRUE,
  );
  // Key pair options.
  $form['additional'] = array(
    '#type' => 'fieldset',
    '#title' => t('Key options'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  // Private PEM key path.
  $form["{$id}_key_private"] = array(
    '#type' => 'textfield',
    '#title' => t('Private key file'),
    '#description' => t('Accessible absolute system path to your private key PEM file.'),
    '#default_value' => variable_get("{$id}_private_key", ''),
    '#required' => TRUE,
  );
  // Private PEM key path.
  $form["{$id}_key_passphrase"] = array(
    '#type' => 'textfield',
    '#title' => t('Private key file'),
    '#description' => t('Private key passphrase in case that your key file is encrypted.'),
    '#default_value' => variable_get("{$id}_key_passphrase", ''),
  );
  // Private PEM key path.
  $form["{$id}_key_public"] = array(
    '#type' => 'textfield',
    '#title' => t('Public key file'),
    '#description' => t('Optional accessible absolute system path to your public key PEM file for verification purposes.'),
    '#default_value' => variable_get("{$id}_key_public", ''),
  );
  // Paypaad gateway URIs.
  $form['additional'] = array(
    '#type' => 'fieldset',
    '#title' => t('Additional options'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  // Paypaad gateway trace URI.
  $form['additional']["{$id}_trace_uri"] = array(
    '#type' => 'textfield',
    '#title' => t('Paypaad gateway controller URI'),
    '#description' => t('Do not change the default value unless you checked that Paypaad docs and it has changed.'),
    '#default_value' => variable_get("{$id}_trace_uri", PAYPAAD_TRACE_URI),
    '#required' => TRUE,
  );
  // Paypaad gateway controller URI.
  $form['additional']["{$id}_controller_uri"] = array(
    '#type' => 'textfield',
    '#title' => t('Paypaad gateway controller URI'),
    '#description' => t('Do not change the default value unless you checked that Paypaad docs and it has changed.'),
    '#default_value' => variable_get("{$id}_controller_uri", PAYPAAD_CONTROLLER_URI),
    '#required' => TRUE,
  );

  return $form;
}

/**
 * UI helper for Paypaad settings form validation process.
 *
 * @param $form
 *   Form array as provided to a form validation callback.
 * @param $form_state
 *   Form state array as provided to a form validation callback.
 */
function paypaad_settings_fields_validate($form, &$form_state, $id = 'paypaad') {
  // Check merchant code for a 9-digit number.
  if (!ctype_digit($form_state['values']["{$id}_merchant"]) || !isset($form_state['values']["{$id}_merchant"][8])) {
    form_set_error("{$id}_merchant", t('Paypaad merchant code must be a 9-digit numeric value.'));
  }
  // Check terminal code for a 10-digit number.
  if (!ctype_digit($form_state['values']["{$id}_terminal"]) || !isset($form_state['values']["{$id}_terminal"][9])) {
    form_set_error("{$id}_terminal", t('Paypaad terminal code must be a 10-digit numeric value.'));
  }
  // Check delivery days for a positive number.
  if (!ctype_digit($form_state['values']["{$id}_max_delivery_days"])) {
    form_set_error("{$id}_max_delivery_days", t('Maximum delivery days must be a positive number.'));
  }
  // Check private key file path.
  if (!is_readable($form_state['values']["{$id}_key_private"])) {
    form_set_error("{$id}_key_private", t('Private key file is not a valid readable file.'));
  }
  // Check public key file path, if set.
  if (!empty($form_state['values']["{$id}_key_public"]) && !is_readable($form_state['values']["{$id}_key_public"])) {
    form_set_error("{$id}_key_public", t('Public key file is not a valid readable file.'));
  }
  // Check gateway trace URL.
  if (!valid_url($form_state['values']["{$id}_trace_uri"], TRUE)) {
    form_set_error("{$id}_trace_uri", t('Paypaad gateway trace URI must be a valid URL.'));
  }
  // Check gateway controller URL.
  if (!valid_url($form_state['values']["{$id}_controller_uri"], TRUE)) {
    form_set_error("{$id}_controller_uri", t('Paypaad gateway controller URI must be a valid URL.'));
  }
}

/**
 * UI helper that injects required hidden fields to the passed form (sub)array.
 *
 * @param $content
 *   XML representation of invoice.
 * @param $sign
 *   Signed copy of invoice XML.
 * @param $form
 *   Form (sub)array.
 *
 * @return
 *   Field injected form (sub)array.
 */
function paypaad_hidden_fields($content, $sign, &$form = array()) {
  // Inject XML representation of invoice.
  $form['content'] = array(
    '#type' => 'hidden',
    '#value' => $content,
  );
  // Then the signed copy.
  $form['sign'] = array(
    '#type' => 'hidden',
    '#value' => $sign,
  );

  return $form;
}

