<?php
// $Id$

/**
 * @file
 * Contains necessary hook implementations, callbacks & helpers.
 */

/**
 * Implements hook_perm().
 */
function paypaad_ui_perm() {
  return array('administer paypaad transactions');
}

/**
 * Implements hook_menu().
 */
function paypaad_ui_menu() {

}

/**
 * Implements hook_views_api().
 */
function paypaad_ui_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'paypaad_ui') . '/views',
  );
}

